"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, FileText, Calendar, AlertTriangle, CheckCircle, Download, Activity } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MedicalTooltip } from "@/components/ui/medical-tooltip";
import { useParams } from "next/navigation";
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ReportDetailsPage() {
  const params = useParams();
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReport();
  }, []);

  const fetchReport = async () => {
    try {
      const res = await fetch('/api/reports');
      const data = await res.json();
      if (data.success) {
        const foundReport = data.reports.find((r: any) => r.id === params.id);
        setReport(foundReport);
      }
    } catch (error) {
      console.error('Failed to fetch report:', error);
    } finally {
      setLoading(false);
    }
  };

  const downloadReport = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(20);
    doc.setTextColor(0, 102, 255);
    doc.text('Medical Report Analysis', 20, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`File: ${report.fileName}`, 20, 30);
    doc.text(`Date: ${new Date(report.uploadDate).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, 20, 36);
    
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('AI Analysis Summary', 20, 50);
    
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const summaryLines = doc.splitTextToSize(report.aiSummary || 'No summary available', 170);
    doc.text(summaryLines, 20, 58);
    
    let yPos = 58 + summaryLines.length * 5 + 10;
    
    // Blood Test Results
    if (report.extractedData?.parameters?.length > 0) {
      const tableData = report.extractedData.parameters.map((param: any) => [
        param.parameter,
        `${param.result} ${param.unit}`,
        `${param.normalRange} ${param.unit}`,
        param.status.toUpperCase()
      ]);
      
      autoTable(doc, {
        startY: yPos,
        head: [['Parameter', 'Result', 'Normal Range', 'Status']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [0, 102, 255], textColor: 255 },
        styles: { fontSize: 9 },
      });
    }
    
    // Radiology Findings
    if (report.extractedData?.radiologyFindings?.length > 0) {
      doc.setFontSize(12);
      doc.text('Radiology Findings', 20, yPos);
      yPos += 10;
      
      report.extractedData.radiologyFindings.forEach((finding: any) => {
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doc.text(`${finding.anatomy}: ${finding.finding} (${finding.severity})`, 20, yPos);
        yPos += 7;
      });
    }
    
    // Clinical Findings
    if (report.extractedData?.clinicalFindings) {
      const cf = report.extractedData.clinicalFindings;
      
      if (cf.vitalSigns && Object.keys(cf.vitalSigns).length > 0) {
        doc.setFontSize(12);
        doc.text('Vital Signs', 20, yPos);
        yPos += 10;
        
        Object.entries(cf.vitalSigns).forEach(([key, value]: [string, any]) => {
          doc.setFontSize(10);
          doc.text(`${key}: ${value}`, 20, yPos);
          yPos += 7;
        });
        yPos += 5;
      }
      
      if (cf.diagnosis && cf.diagnosis.length > 0) {
        doc.setFontSize(12);
        doc.text('Diagnosis', 20, yPos);
        yPos += 10;
        
        cf.diagnosis.forEach((diag: string, i: number) => {
          doc.setFontSize(10);
          const lines = doc.splitTextToSize(`${i + 1}. ${diag}`, 170);
          doc.text(lines, 20, yPos);
          yPos += lines.length * 7;
        });
        yPos += 5;
      }
      
      if (cf.riskFactors && cf.riskFactors.length > 0) {
        doc.setFontSize(12);
        doc.text('Risk Factors', 20, yPos);
        yPos += 10;
        doc.setFontSize(10);
        doc.text(cf.riskFactors.join(', '), 20, yPos);
        yPos += 10;
      }
    }
    
    // Medications
    if (report.extractedData?.medications?.length > 0) {
      doc.setFontSize(12);
      doc.text('Medications', 20, yPos);
      yPos += 10;
      
      report.extractedData.medications.forEach((med: any) => {
        doc.setFontSize(10);
        doc.text(`${med.name} - ${med.dosage}, ${med.frequency}`, 20, yPos);
        yPos += 7;
      });
    }
    
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        'Generated by Medical Report Analysis Platform',
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }
    
    doc.save(`${report.fileName.replace('.pdf', '')}_analysis.pdf`);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="w-12 h-12 border-4 border-[#0066FF] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!report) {
    return (
      <div className="text-center py-12">
        <FileText className="w-16 h-16 text-muted-foreground mx-auto mb-4" />
        <h3 className="text-lg font-semibold text-foreground mb-2">Report not found</h3>
        <Button onClick={() => window.location.href = '/dashboard/reports'}>
          Back to Reports
        </Button>
      </div>
    );
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case "normal": return "bg-green-100 text-green-700 border-green-200";
      case "low": return "bg-yellow-100 text-yellow-700 border-yellow-200";
      case "high": return "bg-orange-100 text-orange-700 border-orange-200";
      case "critical": return "bg-red-100 text-red-700 border-red-200";
      default: return "bg-gray-100 text-gray-700 border-gray-200";
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center gap-4"
      >
        <Button
          variant="ghost"
          onClick={() => window.location.href = '/dashboard/reports'}
          className="rounded-xl"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>
        <div className="flex-1">
          <h1 className="text-3xl font-bold text-foreground">{report.fileName}</h1>
          <p className="text-muted-foreground mt-1">
            Uploaded: {new Date(report.uploadDate).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </div>
        <Button 
          className="bg-[#0066FF] hover:bg-[#0052CC] text-white rounded-xl"
          onClick={downloadReport}
        >
          <Download className="w-4 h-4 mr-2" />
          Download
        </Button>
      </motion.div>

      <motion.div
        className="p-6 rounded-2xl bg-gradient-to-br from-[#0066FF] to-[#0052CC] text-white"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
      >
        <div className="flex items-start gap-4">
          <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center flex-shrink-0">
            <Activity className="w-6 h-6" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold mb-2">Personalized AI Analysis</h3>
            <p className="leading-relaxed text-white/90">{report.aiSummary || 'Analysis in progress...'}</p>
            {report.abnormalCount > 0 && (
              <div className="flex items-center gap-2 mt-4 p-3 rounded-lg bg-yellow-500/20 border border-yellow-300/30">
                <AlertTriangle className="w-4 h-4 text-yellow-200" />
                <span className="text-sm text-yellow-100">
                  {report.abnormalCount} parameter{report.abnormalCount > 1 ? 's' : ''} outside normal range - consult your doctor
                </span>
              </div>
            )}
            {report.abnormalCount === 0 && report.extractedData?.parameters?.length > 0 && (
              <div className="flex items-center gap-2 mt-4 p-3 rounded-lg bg-green-500/20 border border-green-300/30">
                <CheckCircle className="w-4 h-4 text-green-200" />
                <span className="text-sm text-green-100">All parameters within normal range - keep up the good work!</span>
              </div>
            )}
          </div>
        </div>
      </motion.div>

      {report.extractedData?.parameters?.length > 0 ? (
      <motion.div
        className="rounded-2xl bg-white border border-border overflow-hidden"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <div className="p-6 border-b border-border">
          <h3 className="font-semibold text-foreground">Blood Test Results</h3>
          <p className="text-sm text-muted-foreground mt-1">Hover over parameters for detailed explanations</p>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-secondary">
              <tr>
                <th className="px-6 py-4 text-left text-sm font-medium text-muted-foreground">Parameter</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-muted-foreground">Result</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-muted-foreground">Normal Range</th>
                <th className="px-6 py-4 text-left text-sm font-medium text-muted-foreground">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {report.extractedData.parameters.map((param: any, index: number) => (
                <motion.tr
                  key={index}
                  className={param.status !== "normal" ? "bg-yellow-50/50" : ""}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.3 + index * 0.05 }}
                >
                  <td className="px-6 py-4 font-medium text-foreground">
                    <MedicalTooltip term={param.parameter.toLowerCase().split(' ')[0]}>
                      {param.parameter}
                    </MedicalTooltip>
                  </td>
                  <td className="px-6 py-4 text-foreground">
                    {param.result} {param.unit}
                  </td>
                  <td className="px-6 py-4 text-muted-foreground">
                    {param.normalRange} {param.unit}
                  </td>
                  <td className="px-6 py-4">
                    <span className={`inline-flex px-3 py-1 rounded-full text-xs font-medium border ${getStatusColor(param.status)}`}>
                      {param.status.toUpperCase()}
                    </span>
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>
      </motion.div>
      ) : report.extractedData?.radiologyFindings?.length > 0 ? (
      <motion.div
        className="rounded-2xl bg-white border border-border overflow-hidden"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <div className="p-6 border-b border-border">
          <h3 className="font-semibold text-foreground">Radiology Findings</h3>
        </div>
        <div className="p-6 space-y-4">
          {report.extractedData.radiologyFindings.map((finding: any, i: number) => (
            <div key={i} className="p-4 rounded-lg border border-border">
              <div className="flex items-center justify-between mb-2">
                <h4 className="font-medium text-foreground">{finding.anatomy}</h4>
                <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                  finding.severity === 'normal' ? 'bg-green-100 text-green-700' :
                  finding.severity === 'mild' ? 'bg-yellow-100 text-yellow-700' :
                  finding.severity === 'moderate' ? 'bg-orange-100 text-orange-700' :
                  'bg-red-100 text-red-700'
                }`}>
                  {finding.severity.toUpperCase()}
                </span>
              </div>
              <p className="text-muted-foreground text-sm">{finding.finding}</p>
              {finding.impression && (
                <p className="text-xs text-muted-foreground mt-2 italic">{finding.impression}</p>
              )}
            </div>
          ))}
        </div>
      </motion.div>
      ) : report.extractedData?.medications?.length > 0 ? (
      <motion.div
        className="rounded-2xl bg-white border border-border overflow-hidden"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <div className="p-6 border-b border-border">
          <h3 className="font-semibold text-foreground">Prescribed Medications</h3>
        </div>
        <div className="p-6 space-y-4">
          {report.extractedData.medications.map((med: any, i: number) => (
            <div key={i} className="p-4 rounded-lg border border-border">
              <h4 className="font-medium text-foreground mb-2">{med.name}</h4>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="text-muted-foreground">Dosage:</span>
                  <span className="ml-2 text-foreground">{med.dosage}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Frequency:</span>
                  <span className="ml-2 text-foreground">{med.frequency}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Duration:</span>
                  <span className="ml-2 text-foreground">{med.duration}</span>
                </div>
              </div>
              <p className="text-xs text-muted-foreground mt-2">{med.instructions}</p>
            </div>
          ))}
        </div>
      </motion.div>
      ) : report.extractedData?.clinicalFindings ? (
      <motion.div
        className="rounded-2xl bg-white border border-border overflow-hidden"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <div className="p-6 border-b border-border">
          <h3 className="font-semibold text-foreground">Clinical Findings</h3>
        </div>
        <div className="p-6 space-y-6">
          {report.extractedData.clinicalFindings.chiefComplaint && (
            <div>
              <h4 className="font-medium text-foreground mb-2">Chief Complaint</h4>
              <p className="text-muted-foreground">{report.extractedData.clinicalFindings.chiefComplaint}</p>
            </div>
          )}
          {report.extractedData.clinicalFindings.vitalSigns && Object.keys(report.extractedData.clinicalFindings.vitalSigns).length > 0 && (
            <div>
              <h4 className="font-medium text-foreground mb-3">Vital Signs</h4>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {Object.entries(report.extractedData.clinicalFindings.vitalSigns).map(([key, value]: [string, any]) => (
                  <div key={key} className="p-3 rounded-lg bg-blue-50 border border-blue-200">
                    <p className="text-xs text-muted-foreground">{key}</p>
                    <p className="text-lg font-semibold text-foreground">{value}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
          {report.extractedData.clinicalFindings.diagnosis && report.extractedData.clinicalFindings.diagnosis.length > 0 && (
            <div>
              <h4 className="font-medium text-foreground mb-3">Diagnosis / Problems</h4>
              <ul className="space-y-2">
                {report.extractedData.clinicalFindings.diagnosis.map((diag: string, i: number) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="w-6 h-6 rounded-full bg-[#0066FF]/10 flex items-center justify-center text-xs font-medium text-[#0066FF] flex-shrink-0">{i + 1}</span>
                    <span className="text-foreground">{diag}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          {report.extractedData.clinicalFindings.riskFactors && report.extractedData.clinicalFindings.riskFactors.length > 0 && (
            <div>
              <h4 className="font-medium text-foreground mb-3">Risk Factors</h4>
              <div className="flex flex-wrap gap-2">
                {report.extractedData.clinicalFindings.riskFactors.map((risk: string, i: number) => (
                  <span key={i} className="px-3 py-1 rounded-full text-sm bg-yellow-100 text-yellow-700 border border-yellow-200">
                    {risk}
                  </span>
                ))}
              </div>
            </div>
          )}
          {report.extractedData.clinicalFindings.allergies && report.extractedData.clinicalFindings.allergies.length > 0 && (
            <div>
              <h4 className="font-medium text-foreground mb-3">Allergies</h4>
              <div className="flex flex-wrap gap-2">
                {report.extractedData.clinicalFindings.allergies.map((allergy: string, i: number) => (
                  <span key={i} className="px-3 py-1 rounded-full text-sm bg-red-100 text-red-700 border border-red-200">
                    {allergy}
                  </span>
                ))}
              </div>
            </div>
          )}
          {report.extractedData.clinicalFindings.physicalExam && report.extractedData.clinicalFindings.physicalExam.length > 0 && (
            <div>
              <h4 className="font-medium text-foreground mb-3">Physical Examination</h4>
              <ul className="space-y-1">
                {report.extractedData.clinicalFindings.physicalExam.map((exam: string, i: number) => (
                  <li key={i} className="text-muted-foreground text-sm">• {exam}</li>
                ))}
              </ul>
            </div>
          )}
          {report.extractedData.clinicalFindings.medications && report.extractedData.clinicalFindings.medications.length > 0 && (
            <div>
              <h4 className="font-medium text-foreground mb-3">Medications</h4>
              <div className="flex flex-wrap gap-2">
                {report.extractedData.clinicalFindings.medications.map((med: string, i: number) => (
                  <span key={i} className="px-3 py-1 rounded-full text-sm bg-purple-100 text-purple-700 border border-purple-200">
                    {med}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </motion.div>
      ) : (
      <motion.div
        className="p-12 rounded-2xl bg-white border border-border text-center"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <FileText className="w-16 h-16 text-muted-foreground mx-auto mb-4" />
        <h3 className="text-lg font-semibold text-foreground mb-2">Report Processed</h3>
        <p className="text-muted-foreground">
          This report has been analyzed. Check the AI summary above for insights.
        </p>
      </motion.div>
      )}

      <div className="flex items-center gap-6 text-sm">
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-green-500" />
          <span className="text-muted-foreground">Normal</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-yellow-500" />
          <span className="text-muted-foreground">Low</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-orange-500" />
          <span className="text-muted-foreground">High</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-red-500" />
          <span className="text-muted-foreground">Critical</span>
        </div>
      </div>
    </div>
  );
}
